### ISSUE TITLE
Add a Signals API for Binding to Events

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-flask#22]
It would be awesome if this library supported binding to signals for events, stuff like:

- user created
- user logged in
- user updated
- user deleted
- etc

**Comment by bq1990** [comment]
I can't seem to get the user_created signal to work in version 0.4.4. Am I doing something wrong? https://gist.github.com/bq1990/ba145bb6c6115c715c18

**Comment by rdegges** [comment]
Hey @bq1990, here's a working example for ya: https://gist.github.com/rdegges/8de4ec51e2e370246b38
