### ISSUE TITLE
Make the base template configurable

### ISSUE THREAD

**Issue by berendt** [stormpath/stormpath-flask#23]
At the moment it is possible to configure all used templates expect the base template. To change the used base template is it necessary to copy all existing templates, modify `{% extends "flask_stormpath/base.html" %}`, and to set all `STORMPATH_..._TEMPLATE` variables.

**Comment by rdegges** [comment]
Awesome idea. I'll get that into the next release =)

**Comment by rdegges** [comment]
Whoops, accidentally hit the wrong button.

**Comment by rdegges** [comment]
Ok, got this in! You can now specify: STORMPATH_BASE_TEMPLATE in settings to override it =) There's a new release on PyPI!
