### ISSUE TITLE
Full Python 3 Compatibility

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-flask#26]
Would be coolio.

**Comment by avojnovicDk** [comment]
It would, but facebook-sdk is one of the requirements and it is not Python 3 compatible: https://github.com/pythonforfacebook/facebook-sdk/issues/151
> My comments in #148 are still valid. 0.4.0 does not support Python 3. If you need Python 3 support, then you need to use a Git checkout.
> 
> The next version will be 1.0.0.
So currently, there is no facebook-sdk release with Python 3 support. I tried to specify git commit in setup.py for facebook-sdk with fixed Python 3 bugs and it works (tests pass on Python 3.4).
This can only be a temporary fix until facebook-sdk releases 1.0.0 version and shouldn't be released.

**Comment by rdegges** [comment]
@avojnovicDk would you look into this sometime this week? We've been getting more py3k requests, would be cool to see if the facebook stuff is now updated.

**Comment by avojnovicDk** [comment]
@rdegges I'm watching the facebook-sdk repo, so I'm getting notifications all the time. I'll fix this as soon as they release the 1.0.0 version. They have 2 issues left before they release: https://github.com/pythonforfacebook/facebook-sdk/milestones/v1.0.0 and they are also getting requests for Python 3 compatibility, so I'm hoping they will release it soon. I think they had 7 issues until release in March.

**Comment by skunkwerk** [comment]
It doesn't seem like facebook will get updated any time soon - how can I use the temp fix that avojnovicDk suggested?  thanks

**Comment by bnaul** [comment]
Just curious is there a timeframe for a release now that #33, #49, and #57 have all been merged? Seems like this issue is basically resolved but only in master for the time being.

**Comment by rdegges** [comment]
Still waiting for Facebook to do an official release :( That is the only blocker left.

**Comment by bnaul** [comment]
They need to do a release in order to get Facebook functionality actually working, but presently just importing stormpath-flask fails under Python3 regardless of whether you use Facebook or not. So a release right now would at least get things working for Python3 if you aren't using Facebook integration...

**Comment by haveaguess** [comment]
Yeah currently we have forked the release so we can have a stable version of the 'develop' branch that we deploy for python3 use but would be cool if you guys could tag/branch a stable version that we could use we could avoid that

**Comment by rdegges** [comment]
Thanks -- I now understand the issue. I will indeed cut a new release this coming week to solve this for ya'll. Thanks for the input! <3

**Comment by dellintosh** [comment]
:+1: from us on that too, thanks @rdegges for your work on this awesome library!

**Comment by bnaul** [comment]
FYI @rdegges `facebook==1.0.0` is released so if you just bump the version in `setup.py` you can close this...

**Comment by haveaguess** [comment]
@rdegges looking forward to this official support

**Comment by haveaguess** [comment]
Hi guys - can we bump up the version in setup.py and close this ?

**Comment by rdegges** [comment]
This is now 100% done and released. I had to make some test changes to fix broken things before cutting the final release.

**Comment by TeddyHartanto** [comment]
Support for Python 3 is coming out?

**Comment by rdegges** [comment]
This library is now 100% python3 compatible.

**Comment by TeddyHartanto** [comment]
@ohadpartuck Stormpath is now 100% python 3 compatible! Just a day ago! :smiley:

**Comment by GerardoPrada** [comment]
@rdegges The Flask-Stormpath documentation in readthedocs [here](https://flask-stormpath.readthedocs.io/en/latest/setup.html) still says that Flask-Stormpath is "currently only compatible with Python 2.7". (See bottom of linked page). Might be a good idea to update that; I was about to use Flask-Login instead but luckily found this issue before switching

**Comment by bFraley** [comment]
@gerardoprada @rdegges I was about two minutes from disregarding Stormpath when I got to the bottom of http://flask-stormpath.readthedocs.io/en/latest/setup.html#create-a-stormpath-account and noticed the note. I'm very pleased now seeing this issue is resolved!
