### ISSUE TITLE
Broken Error Template (possibly?)

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-flask#29]
Just got a user report saying:

One thing about your templates in python, i don't know if it's like this because wanted to or not but: 

```html
<div class="alert alert-danger"> 
  {% for message in messages %} 
    {{ message }} 
  {% endfor %} 
</div>
```

in login.html, register.html, forgot.html and forgot_change.html

but this is print printing the error dictionary in unicode.

```python
{% for message in messages %} 
  {{ message['message'] }} 
{% endfor %}
```

render much better and print only the error message.

**Comment by BadTasTe-** [comment]
This will actually gives an empty error message if you want to acces to a page with the "@login_required" and no session opened once redirected to the login page.

**Comment by avojnovicDk** [comment]
I changed the code so it flashes only the message value from StormpathError. This way the templates remain the same, so the case @BadTasTe- mentioned will not be broken, and the Stormpath errors problem user reported will be solved.

**Comment by rdegges** [comment]
Cutting a release to fix this right now.
