### ISSUE TITLE
Unable to Install via Pip

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-flask#34]
Since the latest release, where we included the alpha Facebook SDK, users can no longer install this library via pip. I'm not sure why this is failing, but apparently pip won't serve the alpha release of the facebook sdk package unless it's via python setup.py develop.

This is the first time I've seen this.

```
Downloading/unpacking Flask-WTF>=0.9.5 (from flask-stormpath)
  Using download cache from /Users/rdegges/.pip/download/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2FF%2FFlask-WTF%2FFlask_WTF-0.11-py2.py3-none-any.whl
Downloading/unpacking facebook-sdk==1.0.0-alpha (from flask-stormpath)
  Could not find a version that satisfies the requirement facebook-sdk==1.0.0-alpha (from flask-stormpath) (from versions: 0.3.0, 0.3.1, 0.3.2, 0.4.0)
Cleaning up...
No distributions matching the version for facebook-sdk==1.0.0-alpha (from flask-stormpath)
Storing debug log for failure in ~/.pip/pip.log
```

Because this is breaking real apps, I'm reverting to the old facebook-sdk release, and removing python 3 support for now from travis.

**Comment by rdegges** [comment]
@avojnovicDk wanna take a look at this when you get a moment?

**Comment by avojnovicDk** [comment]
I tried many different combinations, but I couldn't get this to work. :(
Basically, if I specify any facebook-sdk 1.0.0 version in install_requires, it will produce the above error - and only when I use pip, python setup.py install works. Unless I specify it as "facebook-sdk<=1.0.0-alpha", then it will install facebook-sdk, but of 0.4.0 version.
The repo owner says that he wouldn't use this alpha version in production: https://github.com/pythonforfacebook/facebook-sdk/issues/162 . I hope that he'll release that 1.0.0 version soon.

**Comment by rdegges** [comment]
Heyo! That's cool -- I propose just waiting until they cut the 1.0.0 release. No biggie.

**Comment by rdegges** [comment]
All done and released!
