### ISSUE TITLE
Add config option to set log level for flask-stormpath module

### ISSUE THREAD

**Issue by lots0logs** [stormpath/stormpath-flask#44]
I'm not even sure if this is possible BUT I thought I couldn't hurt to ask. Basically, I want to be able to set my app's logging level to `DEBUG` without debug messages from flask stormpath module because it's very noisy. If there is some other way I can accomplish this on my own I would appreciate any advice you could offer :smile:

**Comment by rdegges** [comment]
Heyo!

Hmm... So, this Flask library doesn't actually do any logging at all. The underlying Stormpath python library does, though: https://github.com/stormpath/stormpath-sdk-python

It's looks like there's only one line of logging being used, atm: https://github.com/stormpath/stormpath-sdk-python/search?utf8=%E2%9C%93&q=log

Are you seeing the 'Retryable condition detected ...' message a lot? If you're seeing something else, what are you seeing?

**Comment by lots0logs** [comment]
This is what is logged with every request made by a logged in user:
```
"LEVEL: DEBUG\n PATH: /usr/local/lib/python2.7/dist-packages/stormpath/http.py: 142\nMODULE: http\nFUNCTION: request\nDATE: 2015-06-24 17:02:32,954\nMSG: HttpExecutor.request(method=GET, url=https://api.stormpath.com/v1/accounts/5XJG*************SYDN, params=None, data=None) -> [200] {\"href\":\"https://api.stormpath.com/v1/accounts/5XJG*************SYDN\",\"username\":\"lots0logs\",\"email\":\"dustin@falgout.us\",\"givenName\":\"Dustin\",\"middleName\":\"\",\"surname\":\"Falgout\",\"fullName\":\"Dustin Falgout\",\"status\":\"ENABLED\",\"createdAt\":\"2014-10-20T04:22:32.000Z\",\"modifiedAt\":\"2014-12-08T14:30:20.000Z\",\"emailVerificationToken\":null,\"customData\":{\"href\":\"https://api.stormpath.com/v1/accounts/5XJG*************SYDN/customData\"},\"providerData\":{\"href\":\"https://api.stormpath.com/v1/accounts/5XJG*************SYDN/providerData\"},\"directory\":{\"href\":\"https://api.stormpath.com/v1/directories/5XIz*************H1QaFDL3\"},\"tenant\":{\"href\":\"https://api.stormpath.com/v1/tenants/5XIi4a*************Twj1sSj\"},\"groups\":{\"href\":\"https://api.stormpath.com/v1/accounts/5XJG*************SYDN/groups\"},\"applications\":{\"href\":\"https://api.stormpath.com/v1/accounts/5XJG*************SYDN/applications\"},\"groupMemberships\":{\"href\":\"https://api.stormpath.com/v1/accounts/5XJG*************SYDN/groupMemberships\"},\"apiKeys\":{\"href\":\"https://api.stormpath.com/v1/accounts/5XJG*************SYDN/apiKeys\"}}"
```

**Comment by avojnovicDk** [comment]
Hi @lots0logs !
That log message is from Stormpath Python SDK. It uses private logger named 'stormpath.http' for this, so you should be able to disable them with: ```your_logging.getLogger('stormpath.http').setLevel(logging.WARNING)``` .

**Comment by lots0logs** [comment]
@avojnovicDk Wow okay, that's great! Much appreciated! :smile:
