### ISSUE TITLE
does google login for websites work with flask-stormpath?

### ISSUE THREAD

**Issue by markmark1** [stormpath/stormpath-flask#46]
https://developers.google.com/identity/sign-in/web/sign-in i am trying to implement google login for websites
does this work with flask-stormpath if yes is there an example?
If not do you mind giving pointers on how you would solve this - thanks a lot

**Comment by rdegges** [comment]
This is covered in the docs: https://flask-stormpath.readthedocs.org/en/latest/product.html#use-google-login
