### ISSUE TITLE
Tentative release date of new version with stormpath==2.0.7?

### ISSUE THREAD

**Issue by alejom99** [stormpath/stormpath-flask#51]
Is there a tentative date for merging the develop branch into master and making a new release? We're in need of using stormpath-flask with stormpath==2.0.7.

**Comment by jcass77** [comment]
Release [0.4.7](https://github.com/stormpath/stormpath-flask/releases/tag/0.4.7) includes stormpath 2.4.4 - we can probably close this issue.
