### ISSUE TITLE
Default registration view does not confirm user password

### ISSUE THREAD

**Issue by shadowhawk38** [stormpath/stormpath-flask#58]
The built-in view for user registration does not have the user enter their password twice to confirm they entered it correctly. This means if the user mistypes their password during registration, they will appear to be locked out - since they're using the wrong password. This CAN be worked around by rolling custom registration views, but the documentation has that listed as not recommended.

**Comment by rdegges** [comment]
I'm personally NOT a fan of allowing users to enter their password twice. Instead, I think it's a much better UX experience to have the user enter things one time, and then have a nicely configured password reset workflow for users who forget (or mistype) their passwords.

To that end -- I won't be making this the default behavior, sorry!
