### ISSUE TITLE
ExtDeprecationWarning for Flask 0.11.1

### ISSUE THREAD

**Issue by ekcheng** [stormpath/stormpath-flask#72]
Trying to import `flask_stormpath` 0.4.5 when using flask 0.11.1 produces the following warning:

```
python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
  .format(x=modname), ExtDeprecationWarning
```

**Comment by rdegges** [comment]
This has already been fixed in master. Just haven't cut a release yet =) No worries!

**Comment by ekcheng** [comment]
Great! Any timeline on the next release?

**Comment by rdegges** [comment]
I was waiting to cut the release until I merge in some ongoing PRs that are in progress. So maybe a few weeks? It's not a big rush yet, because nothing in the existing release is broken so still going smooth =)
