### ISSUE TITLE
Suppress FlaskWTFDeprecationWarning

### ISSUE THREAD

**Issue by dappiu** [stormpath/stormpath-flask#80]
With a recent update of Flask-WTF this warning is printed out each time the `/login` view is requested:

> FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.

**Comment by rdegges** [comment]
Thanks for bringing this to my attention -- will get this fixed =)

**Comment by jcass77** [comment]
This issue was fixed as part of #90 and #91 and can probably be closed.

**Comment by rdegges** [comment]
Going to cut a new release shortly, with these included. Will close for now and push the new release in a bit.
