### ISSUE TITLE
ImportError: stormpath not able to import '_get_user' from Flask_Login

### ISSUE THREAD

**Issue by lwgray** [stormpath/stormpath-flask#84]
I upgraded to latest versions of flask_stormpath(0.4.6) and flask_login(0.4.0) and an Import Error was thrown because flask_stormpath couldn't import '_get_user' from flask_login

**Comment by jwm** [comment]
Opened https://github.com/stormpath/stormpath-flask/pull/85 to fix this.

For now, workarounds are to downgrade to flask-login 0.3.2, or add this to your app before importing `flask_stormpath`:

```
import flask_login.utils
flask_login._get_user = flask_login.utils._get_user
```

**Comment by rdegges** [comment]
Just merged in the PR with the fix, if you're using develop you should be good before the release comes out.
