### ISSUE TITLE
Customizing error message when trying to access login_required() page without being logged in

### ISSUE THREAD

**Issue by GerardoPrada** [stormpath/stormpath-flask#97]
When trying to access a page marked with the login_required() decorator without being logged in, the following message is displayed in the top left corner of the screen:

- Please log in to access this page.

Can this message be modified? I've tried looking for the place where the message is generated but can not seem to find it. A `grep -r "Please log in to access this page"` in the stormpath-flask dir did not return any results.

Ideally I'd like to modify the error message and if possible, the styling so that it matches the rest of the login page.

**Comment by jcass77** [comment]
I believe the error message is generated by Flask-Login - see https://github.com/maxcountryman/flask-login/blob/7a678346fc43852bf419f00eeeaf9302a2ece862/docs/index.rst#customizing-the-login-process.

**Comment by GerardoPrada** [comment]
Thank you. You are correct, the message is set here: https://github.com/maxcountryman/flask-login/blob/master/flask_login/config.py (see line 25). As per the instructions in your link, the first thing I tried was the following in my `app/__init__.py`:

```
from flask_login import LoginManager
...
def create_app(config_name):
    ...
    stormpath_manager = StormpathManager()
    stormpath_manager.init_app(app)
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_message = u"test"
    ...
```

I suspected that this didn't work because StormpathManager already initializes LoginManager, which is true as seen here: https://github.com/stormpath/stormpath-flask/blob/master/flask_stormpath/__init__.py (line 137). Based on this, I don't see any way to retrieve that `login_manager` object to modify the `login_message`. So is my only option to go into `.../flask_login/config.py` in the flask-login installation in my project's virtual env and modify the message there?

**Comment by jcass77** [comment]
I haven't tested it, but suspect that you can just add ``LOGIN_MESSAGE = 'Your login message.'`` to your Flask application's configuration object - see http://flask.pocoo.org/docs/0.12/config/.

**Comment by GerardoPrada** [comment]
That did not seem to work. I did find a solution that does not involve modifying the flask_login or flask_stormpath files. Based on the template for login.html [here](https://flask-stormpath.readthedocs.io/en/latest/product.html#the-most-basic-templates), I added to following to my login.html:

```
{# Display errors (if there are any). #}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul>
      {% for message in messages %}
        {% if 'Please log in to access this page.' in message %}
          <li>DESIRED ERROR TEXT HERE</li>
        {% else %}
          <li>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
```
